###***********************************************************************************
###*******    Deployment Template for task manager web api****************************
###*********************************************************************************
###********** Please contact Billing CM (asdbillcm@geico.com) for any updates
############Base template referred 
###https://geico.visualstudio.com/PaaS-Serverless/_git/orchestration-templates?path=/src/Web/config/deployment.yaml
# Helm Chart Version
version: 4.7.6  
# Breaking changes .Containers will be run as nonroot users by default as part of security requirements

# namspace should be created prior to deployment.work with platform team to create the namespace
namespacePrefix: "payment" # Namespace prefix will be used for deployment of the componets in the Cluster. Final namespace will include the environment. for instance 'billing' is namespacePrefix and 'dv' is environment then all the components will be deployed in 'billing-dv' namespace in the cluster, And RBAC will be given to this namespace.

tags:           # Tags key value pair (environment, serviceId, componentId, type will be auto included by orchestration)
  tag1: webcomponent  # Custom tags are optional
  tag2: tskapi

containers:
- name: main  # Keep the name of main container unchanged
  type: main
  env:
    - name: HTTPS_PROXY
      value: "http://cnfappproxy.geico.net:80"
    - name: HTTP_PROXY
      value: "http://cnfappproxy.geico.net:80"
    - name: NO_PROXY
      value: ".geico.net,.geicoddc.net"
  ports:
    - containerPort: 30000
      protocol: TCP
      name: http1
  readinessProbe: # Optional readiness probe definition overwrite, the default value will be used if not supplied
    httpGet:
      path: /health/ready
      port: 30000
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
    failureThreshold: 3
  livenessProbe: # Optional liveness probe definition overwrite, the default value will be used if not supplied
    httpGet:
      path: /health/live
      port: 30000
    initialDelaySeconds: 3
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 1
    failureThreshold: 3
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
  volumes: []
    
storage: []

scaling:
  minReplicas: 1
  maxReplicas: 5

apiGatewayEnabled: true

secrets:
  serviceAccountName: svc-vlt-pmttsk-np
  vault.hashicorp.com/role: vr_payments_taskmanager
  vault.hashicorp.com/secret-volume-path: /vault/secrets
  vault.hashicorp.com/agent-inject-secret-secrets.json: 've_payments_taskmanager/data/tskapi_dv1'
  vault.hashicorp.com/agent-inject-template-secrets.json: |
      {{- with secret "ve_payments_taskmanager/data/tskapi_dv1" -}}
      {
        {{- $counter := 1 -}}
        {{- $totalKeys := len .Data.data -}}
        {{- range $key, $value := .Data.data }}
        "{{ $key }}":"{{ $value }}"{{ if ne $counter $totalKeys }},{{ end }}
        {{- $counter = add $counter 1 -}}
        {{- end }}
      }
      {{- end }}