// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	messaging "geico.visualstudio.com/Billing/plutus/common-models/messaging"
	mock "github.com/stretchr/testify/mock"
)

// ExecutionRequestRepositoryInterface is an autogenerated mock type for the ExecutionRequestRepositoryInterface type
type ExecutionRequestRepositoryInterface struct {
	mock.Mock
}

// ExecuteRequests provides a mock function with given fields: executePaymentRequest
func (_m *ExecutionRequestRepositoryInterface) ExecuteRequests(executePaymentRequest messaging.ProcessPaymentRequest) error {
	ret := _m.Called(executePaymentRequest)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteRequests")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(messaging.ProcessPaymentRequest) error); ok {
		r0 = rf(executePaymentRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewExecutionRequestRepositoryInterface creates a new instance of ExecutionRequestRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutionRequestRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutionRequestRepositoryInterface {
	mock := &ExecutionRequestRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
