###***********************************************************************************
###*******    Deployment Template for admapi ****************************
###*********************************************************************************
###********** Please contact Billing CM (asdbillcm@geico.com) for any updates
############Base template referred 
###https://geico.visualstudio.com/PaaS-Serverless/_git/orchestration-templates?path=/src/Web/config/component.dv.yaml
kind: Component
metadata:  
  classification: service.serverless.knative.http
  service:
    name: admapi # Name of the application component
    description: admapi # Description of the application component
    system: bilpmt # Service Id of the application (enterprise acronym)
    component: admapi # Component Id of the application component that uniquely identifies the component
    systemTier: tier # Tier of the application component
    department: PaymentTech # Department of the application componentS
    owner: PaymentTech # Owner of the application component
    dataClassification: "PII" 
    notifications: 
        - paasmvpteam@geico.com
        - asdbillcm@geico.com
        - asdbillingdevopsl2@geico.com
        - AbTripathi@geico.com
        - MKollipara@geico.com
        - nishah@geico.com
        - gpp@geico.com
  placement:
    preference:
      cloudProvider:
        name: "On-Prem" # Azure, On-Prem, AWS





