version: '3'

services:

  payment-administrator-api:
    build:
      context: ./../payment-administrator
      dockerfile: ./../payment-administrator/api/administrator-api.local.dockerfile
    restart: always
    environment:
      environment: docker
    ports:
      - "8081:30000"
      - "9091:5051"
    deploy:
      mode: replicated
      replicas: 1

  payment-vault-api:
    build:
      context: ./../payment-vault
      dockerfile: ./../payment-vault/api/vault-api.local.dockerfile
    restart: always
    environment:
      environment: docker
    ports:
      - "8082:30000"
      - "9092:5051"
    deploy:
      mode: replicated
      replicas: 1

  payment-executor-api:
    build:
      context: ./../payment-executor
      dockerfile: ./../payment-executor/api/executor-api.local.dockerfile
    restart: always
    environment:
      environment: docker
    ports:
      - "8083:30000"
      - "9093:5051"
    deploy:
      mode: replicated
      replicas: 1

  task-manager-api:
    build:
      context: ./../task-manager
      dockerfile: ./../task-manager/api/task-manager-api.local.dockerfile
    restart: always
    environment:
      environment: docker
    ports:
      - "8084:30000"
    deploy:
      mode: replicated
      replicas: 1
  
  config-manager-api:
    build:
      context: ./../config-manager
      dockerfile: ./../config-manager/api/config-manager-api.local.dockerfile
    restart: always
    environment:
      environment: docker
    ports:
      - "8085:30000"
    deploy:
      mode: replicated
      replicas: 1