###***********************************************************************************
###*******    Deployment Template for vltapi ****************************
###*********************************************************************************
###********** Please contact Billing CM (asdbillcm@geico.com) for any updates
############Base template referred 
###https://geico.visualstudio.com/PaaS-Serverless/_git/orchestration-templates?path=/src/Web/config/component.dv.yaml
kind: Component
metadata:  
  classification: service.serverless.knative.http
  service:
    name: vltapi
    description: vltapi
    system: bilpmt
    component: vltapi
    systemTier: tier
    department: PaymentTech
    owner: PaymentTech
    dataClassification: "PII" 
    notifications: 
        - paasmvpteam@geico.com
        - asdbillcm@geico.com
        - asdbillingdevopsl2@geico.com
        - AbTripathi@geico.com
        - MKollipara@geico.com
        - nishah@geico.com
        - gpp@geico.com
  placement:
    preference:
      cloudProvider:
        name: "On-Prem" # Azure, On-Prem, AWS